CREATE OR REPLACE TABLE CUSTOMER_RAW (
    CUSTOMER_ID NUMBER,
    CUSTOMER_NAME STRING,
    EMAIL STRING,
    CITY STRING
);

CREATE OR REPLACE FILE FORMAT CSV_FORMAT
TYPE = CSV;


CREATE OR REPLACE STAGE CUSTOMER_S3_STAGE
URL='s3://snowflake-practical073/'
CREDENTIALS=(
    AWS_KEY_ID='AKIAT3HPLZ6TVUC24BLO'
    AWS_SECRET_KEY='mmM9lgWUQMy+6QidAKCn6LAmYgcAFk0iIzh3T7Fw'
)
FILE_FORMAT = CSV_FORMAT;

list @CUSTOMER_S3_STAGE


COPY INTO CUSTOMER_RAW FROM @CUSTOMER_S3_STAGE

SELECT * FROM CUSTOMER_RAW