CREATE OR REPLACE TABLE CUSTOMER_RAW_1 (
    CUSTOMER_ID NUMBER,
    CUSTOMER_NAME STRING,
    EMAIL STRING,
    CITY STRING
);

CREATE OR REPLACE FILE FORMAT CSV_FORMAT
TYPE = CSV
FIELD_DELIMITER = ','
SKIP_HEADER = 0;

CREATE OR REPLACE STORAGE INTEGRATION S3_INT
TYPE = EXTERNAL_STAGE
STORAGE_PROVIDER = S3
ENABLED = TRUE
STORAGE_AWS_ROLE_ARN = 'arn:aws:iam::264642482087:role/SNOWFLAKES3CONNECT'
STORAGE_ALLOWED_LOCATIONS = ('s3://demo-customer-test03w/');

DESC INTEGRATION S3_INT;

CREATE OR REPLACE STAGE CUSTOMER_S3_STAGE
URL='s3://demo-customer-test03w/'
STORAGE_INTEGRATION = S3_INT
FILE_FORMAT = CSV_FORMAT;

LIST @CUSTOMER_S3_STAGE

COPY INTO CUSTOMER_RAW_1
FROM @CUSTOMER_S3_STAGE;

SELECT * FROM CUSTOMER_RAW_1