CREATE DATABASE RETAIL;
Use RETAIL;
CREATE SCHEMA RAW;

CREATE OR REPLACE TABLE RAW_CUSTOMERS
(
    CUSTOMER_ID      VARCHAR(100),
    CUSTOMER_NAME    VARCHAR(100),
    EMAIL            VARCHAR(200),
    CITY             VARCHAR(100),
    STATE            VARCHAR(50),
    PHONE            VARCHAR(30),
    CREATED_DATE     VARCHAR(100)
);

CREATE OR REPLACE TABLE RAW_PRODUCTS
(
    PRODUCT_ID      VARCHAR(20),
    PRODUCT_NAME    VARCHAR(200),
    CATEGORY        VARCHAR(100),
    BRAND           VARCHAR(100),
    PRICE           VARCHAR(20)
);


CREATE OR REPLACE TABLE RAW_ORDERS
(
    ORDER_ID        VARCHAR(30),
    CUSTOMER_ID     VARCHAR(30),
    ORDER_DATE      VARCHAR(30),
    ORDER_STATUS    VARCHAR(30)
);


CREATE OR REPLACE TABLE RAW_ORDER_ITEMS
(
    ORDER_ID        VARCHAR(20),
    PRODUCT_ID      VARCHAR(20),
    QUANTITY        VARCHAR(20)
);


SELECT * FROM RAW_CUSTOMERS

SELECT * FROM RAW_ORDERS
SELECT * FROM RAW_PRODUCTS
SELECT * FROM RAW_ORDER_ITEMS