CREATE OR REPLACE TABLE EMPLOYEE
(
    EMP_ID INT,
    EMP_NAME STRING,
    SALARY NUMBER
);

INSERT INTO EMPLOYEE VALUES
(1,'Manish',100000),
(2,'Amit',120000);

select * from EMPLOYEE

-- data masking 

CREATE OR REPLACE MASKING POLICY SALARY_MASK
AS (VAL NUMBER)
RETURNS NUMBER ->
CASE
    WHEN CURRENT_ROLE() = 'ACCOUNTADMIN'
        THEN VAL
    ELSE '******'
END;


ALTER TABLE EMPLOYEE
MODIFY COLUMN SALARY
SET MASKING POLICY SALARY_MASK;


USE ROLE ACCOUNTADMIN;

SELECT * FROM EMPLOYEE;

USE ROLE SYSADMIN;

SELECT * FROM EMPLOYEE;