CREATE OR REPLACE TABLE CUSTOMER_NEW (
    CUSTOMER_ID NUMBER,
    CUSTOMER_NAME STRING,
    CITY STRING
);

-- Step 2: Create File Format
CREATE OR REPLACE FILE FORMAT CSV_FORMAT
TYPE = CSV
SKIP_HEADER = 1;


-- Step 3: Create Storage Integration

CREATE OR REPLACE STORAGE INTEGRATION S3_INT
TYPE = EXTERNAL_STAGE
STORAGE_PROVIDER = S3
ENABLED = TRUE
STORAGE_AWS_ROLE_ARN = 'arn:aws:iam::533267206558:role/practicaltest'
STORAGE_ALLOWED_LOCATIONS = ('s3://datapoctesting01/customer/');

DESC INTEGRATION S3_INT;



CREATE OR REPLACE STAGE CUSTOMER_STAGE
URL='s3://datapoctesting01/customer/'
STORAGE_INTEGRATION=S3_INT
FILE_FORMAT=CSV_FORMAT;

LIST @CUSTOMER_STAGE;

CREATE OR REPLACE EXTERNAL TABLE ext_sales_raw
LOCATION=@CUSTOMER_STAGE
FILE_FORMAT=CSV_FORMAT;

SELECT *, VALUE:c1::NUMBER AS customer_id,VALUE:c2::VARCHAR AS customer_name FROM ext_sales_raw



CREATE EXTERNAL TABLE EXT_SALES_1
(
  CUSTOMER_ID NUMBER AS (VALUE:c1::NUMBER),
  CUSTOMER_NAME VARCHAR AS (VALUE:c2::VARCHAR),
  CITY VARCHAR AS (VALUE:c3::VARCHAR)
)
LOCATION=@CUSTOMER_STAGE
FILE_FORMAT=CSV_FORMAT;

SELECT * FROM EXT_SALES_1



