CREATE OR REPLACE TABLE CUSTOMER_NEW (
    CUSTOMER_ID NUMBER,
    CUSTOMER_NAME STRING,
    CITY STRING
);

-- Step 2: Create File Format
CREATE OR REPLACE FILE FORMAT CSV_FORMAT
TYPE = CSV
SKIP_HEADER = 1;


-- Step 3: Create Storage Integration

CREATE OR REPLACE STORAGE INTEGRATION S3_INT
TYPE = EXTERNAL_STAGE
STORAGE_PROVIDER = S3
ENABLED = TRUE
STORAGE_AWS_ROLE_ARN = 'arn:aws:iam::533267206558:role/practicaltest'
STORAGE_ALLOWED_LOCATIONS = ('s3://datapoctesting01/customer/');

DESC INTEGRATION S3_INT;



CREATE OR REPLACE STAGE CUSTOMER_STAGE
URL='s3://datapoctesting01/customer/'
STORAGE_INTEGRATION=S3_INT
FILE_FORMAT=CSV_FORMAT;

LIST @CUSTOMER_STAGE;

--Step 7: Create Snowpipe

CREATE OR REPLACE PIPE CUSTOMER_PIPE
AUTO_INGEST = TRUE
AS
COPY INTO CUSTOMER_NEW
FROM @CUSTOMER_STAGE;

DESC PIPE CUSTOMER_PIPE;

select * from CUSTOMER_NEW;


SELECT SYSTEM$PIPE_STATUS('CUSTOMER_PIPE');

SHOW PIPES;

DESC PIPE CUSTOMER_PIPE;


SELECT *
FROM TABLE(
 INFORMATION_SCHEMA.COPY_HISTORY(
 TABLE_NAME=>'CUSTOMER_NEW',
 START_TIME=>DATEADD(DAY,-1,CURRENT_TIMESTAMP())
 )
);

SELECT *
FROM TABLE(
 INFORMATION_SCHEMA.COPY_HISTORY(
 TABLE_NAME=>'CUSTOMER_NEW',
 START_TIME=>DATEADD(DAY,-1,CURRENT_TIMESTAMP())
 )
)
WHERE STATUS <> 'Loaded';

SELECT *
FROM TABLE(
 VALIDATE(
 CUSTOMER_NEW,
 JOB_ID => '_LAST'
 )
);

list @customer_stage;